Test fixes
csinva/imodels pull request #27
Opened 2021-01-25 08:10 UTC by keyan3

- Fixed an issue where the GitHub build would pass even if the tests actually failed (screenshot below)
<img width="1639" alt="Screen Shot 2021-01-24 at 11 59 12 PM" src="https://user-images.githubusercontent.com/31714528/105677317-8c816280-5ea0-11eb-931a-0ecd61373ca9.png">

- Added missing random seeding in Skope

I skipped testing `predict_proba` for Skope altogether — thought behind this is that even if you write a `predict_proba` that uses `eval_weighted_rule_sum`, it still won't match the predictions since since Skope predicts based only on whether the score is positive or not. I'm not sure if our Skope needs to have this method at all (the original Skope implementation doesn't)

2021-01-25 15:22 UTC, csinva reviewed
Good catch on the test -- this was a big problem.

2021-01-25 15:24 UTC, csinva requested changes
Can you just have predict_proba use eval_weighted_rule_sum (and not use rules_vote at all). https://github.com/csinva/imodels/blob/master/imodels/rule_set/skope_rules.py#L359

2021-01-26 03:34 UTC, keyan3 commented
> Can you just have predict_proba use eval_weighted_rule_sum (and not use rules_vote at all). https://github.com/csinva/imodels/blob/master/imodels/rule_set/skope_rules.py#L359

We can do `self.eval_weighted_rule_sum(X) / weights_sum`  instead of `self.rules_vote(X) / len(self.rules_without_feature_names_)`, but it still won't match the predictions bc `predict` only requires a nonzero score and not a >50% "probability" to classify a point as an outlier

2021-01-26 03:48 UTC, csinva commented
Gotcha, we should def make them match. Why don't we make predict also have a cutoff of 50% -- so both will use self.eval_weighted_rule_sum

2021-01-26 04:14 UTC, keyan3 commented
> Gotcha, we should def make them match. Why don't we make predict also have a cutoff of 50% -- so both will use self.eval_weighted_rule_sum

Changed

2021-01-26 04:41 UTC, merged